# Generated by Django 5.1 on 2024-08-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=1000, null=True)),
                ('location', models.CharField(max_length=1000, null=True)),
                ('text', models.TextField(default=None, null=True)),
                ('target', models.BooleanField(default=False)),
            ],
        ),
    ]
