# Generated by Django 5.1 on 2024-08-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGPTTweets',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(null=True)),
                ('content', models.TextField(default=None, null=True)),
                ('username', models.CharField(max_length=1000, null=True)),
                ('like_count', models.PositiveIntegerField(null=True)),
                ('retweet_count', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
